[[redirects]]
  from = "/consulta/*"
  to = "https://www.receitaws.com.br/v1/cnpj/:splat"
  status = 200
  force = true
[[redirects]]
  from = "/consulta-cpf/*"
  to = "https://kingsearch.me/endpoint/cpf.php?api_key=zWqVX0cwhL&cpf=:splat"
  status = 200
  force = true
[consulta_cpf]
url = "https://kingsearch.me/endpoint/cpf.php?api_key=zWqVX0cwhL&cpf="
metodo = "GET"
timeout = 30

[campos]
cpf = "cpf"
nome = "nome"
nome_mae = "nome_mae"
data_nascimento = "data_nascimento"
endereco = "endereco"
telefone = "telefone"
email = "email"
situacao = "situacao"
data_situacao = "data_situacao"
ultima_atualizacao = "ultima_atualizacao"
